### ISSUE TITLE
'Error detected while processing function <SNR>7_LoadFTPlugin' and others

### ISSUE THREAD

**Issue by mikeyjk** [ludovicchabant/vim-lawrencium#5] opened 2015-02-06 06:26 UTC
Hey! Firstly, this is my preferred mercurial plugin, it seems like what I need - so thank you :).

Secondly, I'm getting the following errors when running 'Hglog --limit 5':

5 more lines
Error detected while processing function <SNR>7_LoadFTPlugin:
line    2:
E518: Unknown option: cole<
Error detected while processing /home/mikey/.vim/bundle/vim-lawrencium/syntax/hglog.vim:
line   18:
E475: Invalid argument: hglogBookmarkPlus     '\v\+' contained conceal
line   19:
E475: Invalid argument: hglogTagSharp         '\v#'  contained conceal
Press ENTER or type command to continue

--

My vundle installs (in case that is relevant), are:

Plugin 'gmarik/Vundle.vim'
Plugin 'fholgado/minibufexpl.vim'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'bling/vim-airline'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'shawncplus/phpcomplete.vim'
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/syntastic'
Plugin 'ludovicchabant/vim-lawrencium'
Plugin 'tpope/vim-surround'
Plugin 'wombat256.vim'
Plugin 'paranoida/vim-airlineish.git'
Plugin 'GertjanReynaert/cobalt2-vim-theme'
Plugin 'gosukiwi/vim-atom-dark'
Plugin 'tomasr/molokai'
Plugin 'vim-scripts/desertEx'
Plugin 'gilsondev/lizard'
Plugin 'ajh17/Spacegray.vim'

**Comment by ludovicchabant** [comment] 2015-02-07 01:08
Hi there!
Mmmh I'm not sure what's wrong here (obviously it's working on my machine :) ). Do you know what's that `LoadFTPlugin` thing? (it's not from Lawrencium). After that error it seems to complain about some problems with the syntax highlighting file that's use for giving colors the the `Hglog` output, but I'm not sure if there's a real problem there, or if it's just problems caused by the first error...

**Comment by mikeyjk** [comment] 2015-02-13 08:10
Thanks for responding ^_^.
Hm I'm not sure what was causing the initial error! That's a bit embarrassing.
However that being said, I've stripped back everything except for vundle and lawrencium and I'm still getting the later part of the error.

    Error detected while processing /home/mikey/.vim/bundle/vim-lawrencium/syntax/hglog.vim:
    line   18:
    E475: Invalid argument: hglogBookmarkPlus     '\v\+' contained conceal
    line   19:
    E475: Invalid argument: hglogTagSharp         '\v#'  contained conceal

With the only thing in my .vimrc now being:

    set nocompatible
    filetype off
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    Plugin 'gmarik/Vundle.vim'
    Plugin 'ludovicchabant/vim-lawrencium

**Comment by ludovicchabant** [comment] 2015-02-14 16:35
Hi!
So I can't reproduce this error so far... is the repository you're working on public in any way? Maybe it has a combination of tags and bookmarks and stuff that produces the error? (I'm often working on simple repos) Maybe if I cloned that repo I would be able to see the error?

**Comment by mikeyjk** [comment] 2015-02-15 15:29
unfortunately not :(

closed source repository sadly. using 'kiln'.
I wouldn't describe it as a 'simple' repo, but I have limited production experience so I can't really compare it intelligently.

**Comment by ludovicchabant** [comment] 2015-02-21 00:47
Mmmmh ok so how about you run `hg log --limit 5 --style <path to hg_log.style>` (where `hg_log.style` is in the `resources` directory of lawrencium), and you post this here? (or put it up as a gist or pastebin or whatever?). You can of course change the commit messages with some Lorem Ipsum stuff if there's confidential info.
It looks like I would get that error if I then loaded that text in Vim and set the syntax highlighting to use `hglog.vim`, which would make it possible to fix.
(my guess is that you somehow have a few commits whose combination of tags/bookmarks/branches somehow causes the syntax highlighting rules to fail)

**Comment by ludovicchabant** [comment] 2015-11-23 05:51
I'll close this for now -- reopen if you're coming back this way :)

**Closed by ludovicchabant** 2015-11-23 05:51 UTC
